Various updates on initial site content
augrim/augrim-docs pull request #6
Opened 2022-05-18 20:20 UTC by vaporos

2022-05-18 20:48 UTC, peterschwarz approved these changes, later dismissed

2022-05-18 21:04 UTC, rbuysse requested changes

2022-05-18 21:04 UTC, rbuysse commented on community/submissions.md
> +  against the current master branch. Do not merge the current master branch
s/master/main?

2022-05-18 21:04 UTC, rbuysse commented on community/planning/roadmap.md
> +  Copyright 2022 Cargill Incorporated
This doesn't match the range copyrights we have on the rest of the files.

2022-05-18 21:04 UTC, rbuysse commented on community/licensing.md
> +  Copyright 2018-2022 Cargill Incorporated
Should this be 2021-2022 like the rest of the files?

2022-05-23 14:31 UTC, vaporos commented on community/submissions.md
> +  against the current master branch. Do not merge the current master branch
Fixed - we should update splinter-docs too.

2022-05-23 14:34 UTC, vaporos commented on community/planning/roadmap.md
> +  Copyright 2022 Cargill Incorporated
Adjusted this.

2022-05-23 14:34 UTC, vaporos commented on community/licensing.md
> +  Copyright 2018-2022 Cargill Incorporated
The file is older than 2021, so left the copyright statement as-is.

2022-05-23 18:59 UTC, rbuysse approved these changes

2022-05-23 19:01 UTC, peterschwarz approved these changes

2022-05-23 20:00 UTC, merged